/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  PhplistSubscribeForm as PhplistSubscribeForm
} from './components/phplist-subscribe-form/phplist-subscribe-form';

declare global {
  interface HTMLPhplistSubscribeFormElement extends PhplistSubscribeForm, HTMLElement {
  }
  var HTMLPhplistSubscribeFormElement: {
    prototype: HTMLPhplistSubscribeFormElement;
    new (): HTMLPhplistSubscribeFormElement;
  };
  interface HTMLElementTagNameMap {
    "phplist-subscribe-form": HTMLPhplistSubscribeFormElement;
  }
  interface ElementTagNameMap {
    "phplist-subscribe-form": HTMLPhplistSubscribeFormElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "phplist-subscribe-form": JSXElements.PhplistSubscribeFormAttributes;
    }
  }
  namespace JSXElements {
    export interface PhplistSubscribeFormAttributes extends HTMLAttributes {
      action?: string;
    }
  }
}

